version: "3.8"

services:
  db:
    image: postgres:16
    container_name: ex02_db
    environment:
      POSTGRES_USER: abin-saa
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - ex02_data:/var/lib/postgresql/data
      - ./customer:/customer
      - ./table.sh:/docker-entrypoint-initdb.d/table.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abin-saa -d piscineds"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  ex02_data:

