version: "3.8"

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: piscineds_postgres
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - piscineds_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  db_viewer:
    image: dpage/pgadmin4:8
    container_name: piscineds_pgadmin
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_home:/var/lib/pgadmin
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  piscineds_data:
  pgadmin_home:

